# Create environment:
# $ conda create --name <env> --file <this file>

#dependencies:
  - conda
  - python=3.9
  - python.app
  - conda-env
  - conda-build
  - conda-verify
  - _ipyw_jlab_nb_ext_conf
  - anaconda
  - anaconda-navigator==2.2.0
  - navigator-updater
  - s3fs=0.4.2
  - flask=2.0.3
  - awscli=1.22.101
  - eli5=0.13.0
  - joblib=1.1.0
  - json5=0.9.6
  - matplotlib=3.5.1
  - numpy=1.21.5
  - pandas=1.4.2
  - plotly=5.6.0
  - s3fs=0.4.2
  - scipy=1.7.3
  - seaborn=0.11.2
  - shap=0.39.0
  - statsmodels=0.13.2
  - imbalanced-learn==0.9.1
  - imblearn==0.0
  - keras==2.9.0
  - keras-preprocessing==1.1.2
  - scikit-learn==1.1.1
  - sklearn==0.0
  - sodapy==2.1.1
  - tensorflow==2.9.1
  - xgboost==1.6.1